### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by dsancho** [JetBrains/JetBox#10]
I have installed on R# 9.1 but nothing happens. When I click on the links, no browser it's open. I had it already installed for version 9.0 and it worked fine (I have in dropbox the JetBox folder).

**Comment by LordJZ** [comment]
Same, but never used JetBox before. Tried admin & non-admin VS, never worked. Default browser is firefox.

**Comment by YoeriVD** [comment]
Same for me, VS2013 & VS2015

**Comment by mmoore99** [comment]
Same for me, VS2013 & VS2015

**Comment by olegtarasov** [comment]
Doesn't work for me either. Updated from resharper 9.0.

**Comment by derigel23** [comment]
Fixed version is on the gallery https://resharper-plugins.jetbrains.com/packages/ReSharper.JetBox/0.3.7
