### ISSUE TITLE
Unable to resolve dependency error

### ISSUE THREAD

**Issue by kmac23va** [JetBrains/JetBox#13]
This is Visual Studio 2015 with ReSharper 10 on Windows 10. When I try to install Jetbox, I get this error:

ExtensionManagerViewModelProvider | Unable to resolve dependency 'RestSharp (≥ 105.0.1)'.

The plugin worked fine with ReSharper 9.2.

Thanks.

**Comment by derigel23** [comment]
@kmac23va fixed in the gallery. Please, try again.

**Comment by kmac23va** [comment]
Looks good, thanks!
