### ISSUE TITLE
Support for Resharper 2017.2

### ISSUE THREAD

**Issue by Gitii** [JetBrains/JetBox#14]
Hi,

I would like to use this extension but it is outdated and does not show up in the extension gallery.
Is it possible to upgrade this extension?
Or is there an alternative?

Thanks,
Gitii

**Comment by derigel23** [comment]
@Gitii 0.13.3.1 version is released in resharper gallery. please, check.

**Comment by Gitii** [comment]
I checked the extension manager and the plugin does not show up (same for another machine, identical version and vs 2017).
Just a gues:
The gallery "homepage" of jetbox lists three dependencies. The required version of DropNet is 1.10.23 but the newest version available for download is 1.9.6.
